# Find WDK
#
# This module defines
#  WINDDK_FOUND
#  LIBFREESPACE_LIBFREESPACE_WINDDK_DIR
#  WINDDK_INCLUDE_DIR
#  WINDDK_LIBRARIES
#
#

# log message
IF (NOT WINDDK_FIND_QUIETLY)
	MESSAGE(STATUS "Checking for MS Windows Driver Development Kit")
ENDIF()

# If WINDDK_DIR was defined in the environment, use it.
if (NOT LIBFREESPACE_WINDDK_DIR AND NOT $ENV{WINDDK_DIR} STREQUAL "")
  set(LIBFREESPACE_WINDDK_DIR $ENV{LIBFREESPACE_WINDDK_DIR})
endif()

# If WDK_DIR was defined in the environment, use it.
# Commented out because this is dangerous - WDK is not exactly the same as WinDDK
#if (NOT LIBFREESPACE_WINDDK_DIR AND NOT $ENV{WDK_DIR} STREQUAL "")
#  set(LIBFREESPACE_WINDDK_DIR $ENV{WDK_DIR})
#endif()


# If the WinDDK was not defined in the environment variables, take a couple guesses about where it could be
# It only looks for the version 7, i.e. ~/WinDDK/7*
IF(NOT LIBFREESPACE_WINDDK_DIR AND EXISTS "C:/WinDDK" AND IS_DIRECTORY "C:/WinDDK")
  FILE(GLOB LIBFREESPACE_WINDDK_DIR "C:/WinDDK/7*")
ENDIF()
IF(NOT LIBFREESPACE_WINDDK_DIR AND EXISTS "C:/Program Files/WinDDK" AND IS_DIRECTORY "C:/Program Files/WinDDK")
  FILE(GLOB LIBFREESPACE_WINDDK_DIR "C:/Program Files/WinDDK/7*")
ENDIF()
IF(NOT LIBFREESPACE_WINDDK_DIR AND EXISTS "C:/Program Files (x86)/WinDDK" AND IS_DIRECTORY "C:/Program Files (x86)/WinDDK")
  FILE(GLOB LIBFREESPACE_WINDDK_DIR "C:/Program Files (x86)/WinDDK/7*")
ENDIF()

# concat all the search paths
IF(LIBFREESPACE_WINDDK_DIR)
	SET(WINDDK_INCLUDE_SEARCH_DIRS
	  ${WINDDK_INCLUDE_SEARCH_DIRS}
	  ${LIBFREESPACE_WINDDK_DIR}/inc
  )
  SET(WINDDK_LIBRARY_SEARCH_DIRS 
    ${WINDDK_LIBRARY_SEARCH_DIRS}
    ${LIBFREESPACE_WINDDK_DIR}/lib/win7/i386/
  )
ENDIF()

# Search for header files
FIND_PATH(WINDDK_INCLUDE_DIR api #hidpi.h
  PATHS ${WINDDK_INCLUDE_SEARCH_DIRS})

# Search for libraries files
FIND_LIBRARY(WINDDK_HID_LIBRARY hid.lib
  PATHS ${WINDDK_LIBRARY_SEARCH_DIRS})
FIND_LIBRARY(WINDDK_SETUPAPI_LIBRARY setupapi
  PATHS ${WINDDK_LIBRARY_SEARCH_DIRS})

# Configure libraries
SET(LIBFREESPACE_WINDDK_DIR ${LIBFREESPACE_WINDDK_DIR} CACHE PATH "The WINDDK path for Windows 32-bit builds")
SET(WINDDK_INCLUDE_DIR ${WINDDK_INCLUDE_DIR} CACHE STRING "Directory containing Ms WinDDK header files")
SET(WINDDK_LIBRARIES "${WINDDK_HID_LIBRARY}" "${WINDDK_SETUPAPI_LIBRARY}" CACHE STRING "Ms WinDDK libraries files" FORCE)

# Hide those variables in GUI
SET(WINDDK_INCLUDE_DIR ${WINDDK_INCLUDE_DIR} CACHE INTERNAL "")
SET(WINDDK_HID_LIBRARY ${WINDDK_HID_LIBRARY} CACHE INTERNAL "")
SET(WINDDK_SETUPAPI_LIBRARY ${WINDDK_SETUPAPI_LIBRARY} CACHE INTERNAL "")
SET(WINDDK_LIBRARIES ${WINDDK_LIBRARIES} CACHE INTERNAL "")

IF(WINDDK_INCLUDE_DIR AND WINDDK_HID_LIBRARY AND WINDDK_SETUPAPI_LIBRARY)
	SET(WINDDK_FOUND TRUE)
ELSE()
  SET(WINDDK_FOUND FALSE)
ENDIF()

# log find result
IF(NOT FIND_WINDDK_QUIETLY)
  IF(WINDDK_FOUND)
	   MESSAGE(STATUS "WinDDK in ${LIBFREESPACE_WINDDK_DIR}")
  ELSE()
	   MESSAGE(FATAL_ERROR "Could not locate WinDDK - Specify path using the LIBFREESPACE_WINDDK_DIR variable")
  ENDIF()
ENDIF()